on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: executable gradlew
        run: chmod +x gradlew
      - name: Publish Gradle Plugins
        run: |
          ./gradlew assemble publishPlugins \
          -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
          -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
